env: dev
pid: ""
level: 4
log: /dev/stdout

debug:
  addr: 127.0.0.1:12000
  read_timeout: 0s
  write_timeout: 0s
  idle_timeout: 0s
  shutdown_timeout: 0s

http:
  main:
    addr: 127.0.0.1:8080
    read_timeout: 0s
    write_timeout: 0s
    idle_timeout: 0s
    shutdown_timeout: 0s

maxminddb: ./GeoIP2-Country-Test.mmdb
